"""empty message

Revision ID: 3336462f9238
Revises: 6d94a7f035d6
Create Date: 2023-12-12 07:49:41.366366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3336462f9238'
down_revision = '6d94a7f035d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cust', schema=None) as batch_op:
        batch_op.drop_index('ix_cust_email')
        batch_op.create_index(batch_op.f('ix_cust_email'), ['email'], unique=False)
        batch_op.drop_index('ix_cust_name')
        batch_op.create_index(batch_op.f('ix_cust_name'), ['name'], unique=False)
        batch_op.drop_index('ix_cust_orders_list')
        batch_op.create_index(batch_op.f('ix_cust_orders_list'), ['orders_list'], unique=False)

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_index('ix_item_desc')
        batch_op.create_index(batch_op.f('ix_item_desc'), ['desc'], unique=False)
        batch_op.drop_index('ix_item_name')
        batch_op.create_index(batch_op.f('ix_item_name'), ['name'], unique=False)
        batch_op.drop_index('ix_item_ordered_by')
        batch_op.create_index(batch_op.f('ix_item_ordered_by'), ['ordered_by'], unique=False)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index('ix_order_address')
        batch_op.create_index(batch_op.f('ix_order_address'), ['address'], unique=False)
        batch_op.drop_index('ix_order_cust_email')
        batch_op.create_index(batch_op.f('ix_order_cust_email'), ['cust_email'], unique=False)
        batch_op.drop_index('ix_order_name')
        batch_op.create_index(batch_op.f('ix_order_name'), ['name'], unique=False)
        batch_op.drop_index('ix_order_service_or_stock')
        batch_op.create_index(batch_op.f('ix_order_service_or_stock'), ['service_or_stock'], unique=False)
        batch_op.drop_index('ix_order_stock_bought')
        batch_op.create_index(batch_op.f('ix_order_stock_bought'), ['stock_bought'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_stock_bought'))
        batch_op.create_index('ix_order_stock_bought', ['stock_bought'], unique=False)
        batch_op.drop_index(batch_op.f('ix_order_service_or_stock'))
        batch_op.create_index('ix_order_service_or_stock', ['service_or_stock'], unique=False)
        batch_op.drop_index(batch_op.f('ix_order_name'))
        batch_op.create_index('ix_order_name', ['name'], unique=False)
        batch_op.drop_index(batch_op.f('ix_order_cust_email'))
        batch_op.create_index('ix_order_cust_email', ['cust_email'], unique=False)
        batch_op.drop_index(batch_op.f('ix_order_address'))
        batch_op.create_index('ix_order_address', ['address'], unique=False)

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_ordered_by'))
        batch_op.create_index('ix_item_ordered_by', ['ordered_by'], unique=False)
        batch_op.drop_index(batch_op.f('ix_item_name'))
        batch_op.create_index('ix_item_name', ['name'], unique=False)
        batch_op.drop_index(batch_op.f('ix_item_desc'))
        batch_op.create_index('ix_item_desc', ['desc'], unique=False)

    with op.batch_alter_table('cust', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cust_orders_list'))
        batch_op.create_index('ix_cust_orders_list', ['orders_list'], unique=False)
        batch_op.drop_index(batch_op.f('ix_cust_name'))
        batch_op.create_index('ix_cust_name', ['name'], unique=False)
        batch_op.drop_index(batch_op.f('ix_cust_email'))
        batch_op.create_index('ix_cust_email', ['email'], unique=False)

    # ### end Alembic commands ###
