"""empty message

Revision ID: 6d94a7f035d6
Revises: 8322a6a0bc47
Create Date: 2023-12-12 07:45:17.411996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d94a7f035d6'
down_revision = '8322a6a0bc47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cust', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.Integer(), nullable=True))
        batch_op.drop_column('count')
        batch_op.drop_column('cost')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=500), nullable=True))
        batch_op.create_index(batch_op.f('ix_order_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_name'))
        batch_op.drop_column('name')

    with op.batch_alter_table('cust', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('count', sa.INTEGER(), nullable=True))
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
