"""empty message

Revision ID: 8322a6a0bc47
Revises: 33fffadc400c
Create Date: 2023-12-10 14:04:15.614235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8322a6a0bc47'
down_revision = '33fffadc400c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cust',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=500), nullable=True),
    sa.Column('orders_list', sa.String(length=500), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cust', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cust_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_cust_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_cust_orders_list'), ['orders_list'], unique=True)

    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('desc', sa.String(length=500), nullable=True),
    sa.Column('ordered_by', sa.String(length=500), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_desc'), ['desc'], unique=True)
        batch_op.create_index(batch_op.f('ix_item_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_item_ordered_by'), ['ordered_by'], unique=True)

    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cust_email', sa.String(length=500), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('stock_bought', sa.String(length=500), nullable=True),
    sa.Column('service_or_stock', sa.String(length=500), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_address'), ['address'], unique=True)
        batch_op.create_index(batch_op.f('ix_order_cust_email'), ['cust_email'], unique=True)
        batch_op.create_index(batch_op.f('ix_order_service_or_stock'), ['service_or_stock'], unique=True)
        batch_op.create_index(batch_op.f('ix_order_stock_bought'), ['stock_bought'], unique=True)

    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('requested_by', sa.String(length=500), nullable=True),
    sa.Column('email_cust', sa.String(length=500), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_email_cust'), ['email_cust'], unique=True)
        batch_op.create_index(batch_op.f('ix_service_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_service_requested_by'), ['requested_by'], unique=True)

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_index('ix_property_address')

    op.drop_table('property')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('address', sa.VARCHAR(length=500), nullable=True),
    sa.Column('start_date', sa.DATETIME(), nullable=True),
    sa.Column('duration', sa.INTEGER(), nullable=True),
    sa.Column('rent', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.create_index('ix_property_address', ['address'], unique=False)

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_requested_by'))
        batch_op.drop_index(batch_op.f('ix_service_name'))
        batch_op.drop_index(batch_op.f('ix_service_email_cust'))

    op.drop_table('service')
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_stock_bought'))
        batch_op.drop_index(batch_op.f('ix_order_service_or_stock'))
        batch_op.drop_index(batch_op.f('ix_order_cust_email'))
        batch_op.drop_index(batch_op.f('ix_order_address'))

    op.drop_table('order')
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_ordered_by'))
        batch_op.drop_index(batch_op.f('ix_item_name'))
        batch_op.drop_index(batch_op.f('ix_item_desc'))

    op.drop_table('item')
    with op.batch_alter_table('cust', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cust_orders_list'))
        batch_op.drop_index(batch_op.f('ix_cust_name'))
        batch_op.drop_index(batch_op.f('ix_cust_email'))

    op.drop_table('cust')
    # ### end Alembic commands ###
