"""empty message

Revision ID: a30f4d50ff17
Revises: 3336462f9238
Create Date: 2023-12-13 14:35:55.776416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a30f4d50ff17'
down_revision = '3336462f9238'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_index('ix_service_email_cust')
        batch_op.drop_index('ix_service_name')
        batch_op.drop_index('ix_service_requested_by')

    op.drop_table('service')
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_or_stock', sa.String(length=500), nullable=True))
        batch_op.drop_index('ix_item_desc')
        batch_op.create_index(batch_op.f('ix_item_service_or_stock'), ['service_or_stock'], unique=False)
        batch_op.drop_column('desc')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index('ix_order_service_or_stock')
        batch_op.drop_column('service_or_stock')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_or_stock', sa.VARCHAR(length=500), nullable=True))
        batch_op.create_index('ix_order_service_or_stock', ['service_or_stock'], unique=False)

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desc', sa.VARCHAR(length=500), nullable=True))
        batch_op.drop_index(batch_op.f('ix_item_service_or_stock'))
        batch_op.create_index('ix_item_desc', ['desc'], unique=False)
        batch_op.drop_column('service_or_stock')

    op.create_table('service',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=500), nullable=True),
    sa.Column('requested_by', sa.VARCHAR(length=500), nullable=True),
    sa.Column('email_cust', sa.VARCHAR(length=500), nullable=True),
    sa.Column('cost', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.create_index('ix_service_requested_by', ['requested_by'], unique=False)
        batch_op.create_index('ix_service_name', ['name'], unique=False)
        batch_op.create_index('ix_service_email_cust', ['email_cust'], unique=False)

    # ### end Alembic commands ###
